<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net9.0-ios</TargetFrameworks>
    <RootNamespace>N_m3u8DL_RE.Core</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>13.0</LangVersion>
    <Nullable>enable</Nullable>
    <Version>0.5.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\N_m3u8DL-RE.Common\N_m3u8DL-RE.Common.csproj" />
    <ProjectReference Include="..\N_m3u8DL-RE.Parser\N_m3u8DL-RE.Parser.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NiL.JS" Version="2.6.1706" />
  </ItemGroup>

</Project>
